### ISSUE TITLE
Point users to synphot and archive this repository?

### ISSUE THREAD

**Issue by pllim** [bmorris3/tynt#11]
Follow-up of https://github.com/spacetelescope/synphot_refactor/pull/257 and #8.

If you want to go ahead with this, I can make a new `synphot` release with the feature. There is no rush on my end.

**Comment by bmorris3** [comment]
Given I have still found a few uses for this repo, I'm going to keep it alive. If you'd like to add a mention to pysynphot in the tynt docs, PRs are welcome. Thansk!

**Comment by pllim** [comment]
@bmorris3 , I am curious, what prevented you from using the `synphot` port?
