### ISSUE TITLE
Use quantity as an interface layer

### ISSUE THREAD

**Issue by eteq** [bmorris3/tynt#4]
I notice that both the reconstruction and "real" transmittence use x-axes that are hard-coded as angstroms. Better would be for them to be `Quantities` (and `QTable` for hte "real" one), with `angstrom` units.  User can always do .value if they really just need a raw array, but that way the units get carried around

(indirectly related to #1 in that units support is pretty straightforward if a model is used)

**Comment by bmorris3** [comment]
Done!
