### ISSUE TITLE
Include code to generate the reconstructions in the package

### ISSUE THREAD

**Issue by eteq** [bmorris3/tynt#6]
Right now the reconstruction is in notebooks, which makes sense since that was the starting point.  But eventually it would be good for the reconstruction code to live in the repo itself.  Could be done with #1, since that's basically a "fitting" process (although that might be overkill).

And related to that there should be a test that first downloads the "true" model, generates the reconstruction, and compares that to the saved reconstruction to show that the whole thing round-trips.

**Comment by bmorris3** [comment]
The code for Fourier decomposition is now squished into a few methods on the `FilterGenerator` object, and a brief tutorial on how to use them sits in [this repurposed notebook](https://github.com/bmorris3/tynt/blob/master/notebooks/assemble.ipynb).

Still to do: add docstrings on the methods, add brief tutorial in the narrative docs.

**Comment by bmorris3** [comment]
[Code now included with docstrings and examples](https://tynt.readthedocs.io/en/latest/customarchive.html).
